[package]
name = "mipha"
version = "0.1.0"
authors = ["twocucao <twocucao@gmail.com>"]
edition = "2018"

[lib]
name = "mipha"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]

[dependencies]
qrcode = "0.11"
image = "0.23.4"
