[package]
name = "mipha"
version = "0.1.0"
authors = ["twocucao <twocucao@gmail.com>"]
edition = "2018"
description = "A Python wrapper for the Rust API for purposes of testing"


[lib]
name = "mipha"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]

[dependencies]
digest = "0.9.0"


[package.metadata.maturin.scripts]
get_42 = "mipha:get_42"

[package.metadata.maturin]
requires-dist = ["flask~=1.1.0", "toml==0.10.0"]
classifier = ["Programming Language :: Python"]
