[package]
name = "mipha"
version = "0.1.0"
authors = ["twocucao <twocucao@gmail.com>"]
edition = "2018"
description = "A Python wrapper for the Rust API for purposes of testing"


[lib]
name = "mipha"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]

[dependencies]
digest = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
log = "~0.4"
pyo3-log = "0.1.2"
